apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimziapp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'git@github.com:PoornachandS/argocd.git'
    targetRevision: HEAD
    path: apk-cluster/strimzi-apk-cluster
  destination:
    name: https://kubernetes.default.svc
    namespace: strimzi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true