apiVersion: v1
kind: Secret
metadata:
  name: ingress-nginx-admission
  namespace: ingress-nginx
  annotations:
    kubernetes.io/service-account.name: "ingress-nginx-admission"
type: kubernetes.io/service-account-token
