name: build

on:
  push:
    branches:
      - '*'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: 'projects/960983931488/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'iac-196@silver-bird-378013.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - id: get-gke-credentials
        uses: google-github-actions/get-gke-credentials@v0.4.0
        with:
          cluster_name: app-cluster
          location: us-central1

      - id: run-argocd
        run: kubectl apply -f ./argo-cd-appconfig/dev/
