name: build

on:
  push:
    branches:
      - '*'

jobs:
  apply-argo-files:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: 'projects/960983931488/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'iac-196@silver-bird-378013.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - id: bastion-host
        run: |
          gcloud compute ssh --zone "us-central1-a" "app-cluster-bastion"  --project "silver-bird-378013"
          echo "list-files"
          ls
          CLEAN_REF=${GITHUB_REF#refs/tags/}
          CLEAN_REF=${CLEAN_REF#refs/heads/}

          if [ "${CLEAN_REF}" == "main" ]; then
            git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
            git config --global user.email "${GITHUB_ACTOR}@ci"
            git config --global user.name "${GITHUB_ACTOR}"

            git checkout main
            git pull github main
            gcloud container clusters get-credentials app-cluster --region us-central1 --project silver-bird-378013
            kubectl apply -f ./argo-cd-appconfig/dev/
          fi
