apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-cert
  namespace: flask-pub-sub
spec:
  domains:
    - poorna.braveokafor.com
    - www.poorna.braveokafor.com

---

apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: https-redirect
  namespace: flask-pub-sub
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
