apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: HEAD
    path: manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: flask-pub-sub
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
