apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-cert-argo
  namespace: argocd
spec:
  domains:
    - argo.poorna.braveokafor.com
    - www.argo.poorna.braveokafor.com

---

apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: https-redirect-argo
  namespace: argocd
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
